#!/bin/bash

APP_NAME=kde-plasma-mail-checker
APP_VERSION=`cat ./VERSION`

cd ..
cp -f -r ./$APP_NAME ./$APP_NAME-$APP_VERSION
rm -rf ./$APP_NAME-$APP_VERSION/.git
rm -rf ./$APP_NAME-$APP_VERSION/.gitignore
rm -rf ./$APP_NAME-$APP_VERSION/packet
find ./$APP_NAME-$APP_VERSION -type f -name *.pyc -exec rm -f {} \;
find ./$APP_NAME-$APP_VERSION -type f -name *.pyo -exec rm -f {} \;
tar cfj $APP_NAME-$APP_VERSION.tar.bz2 ./$APP_NAME-$APP_VERSION
rm -rf ./$APP_NAME-$APP_VERSION
