#!/bin/bash

APP_NAME=kde-plasma-mail-checker
APP_VERSION=`cat ./VERSION`

cd ..
cp -f -r ./$APP_NAME ./$APP_NAME-$APP_VERSION
rm -rf ./$APP_NAME-$APP_VERSION/.git
rm -rf ./$APP_NAME-$APP_VERSION/.gitignore
rm -rf ./$APP_NAME-$APP_VERSION/packet
rm -rf ./$APP_NAME-$APP_VERSION/make-source-archive
rm -rf ./$APP_NAME-$APP_VERSION/$APP_NAME.spec
rm -rf ./$APP_NAME-$APP_VERSION/Makefile
find ./$APP_NAME-$APP_VERSION -type f -name *.pyc -exec rm -f {} \;
find ./$APP_NAME-$APP_VERSION -type f -name *.pyo -exec rm -f {} \;
tar cfj $APP_NAME-$APP_VERSION.tar.bz2 ./$APP_NAME-$APP_VERSION
rm -rf ./$APP_NAME-$APP_VERSION

RPMBUILD_ROOT=$(cat ~/.rpmmacros | grep "%_topdir" | awk '{print $3}' | sed s/\$HOME\)/\./)
cp -f $APP_NAME-$APP_VERSION.tar.bz2 $RPMBUILD_ROOT/SOURCES
cp -f ~/$APP_NAME/$APP_NAME.spec $RPMBUILD_ROOT/SPECS
cd $RPMBUILD_ROOT/SPECS
/usr/bin/rpmbuild -ba $APP_NAME.spec
